"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

import Layout from "@/components/Layout/Layout";
import { RecoilRoot } from "recoil";

const metadata = {
  title: "Reddit-clone",
  description: "Generated by Aman with help of shaddie sir",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </RecoilRoot>
      </body>
    </html>
  );
}
